--CREATE A FUNCTION TO AUTO-GENERATE 5-CHARACTER ALPHANUMERIC ID
CREATE FUNCTION GENERATEID 
       (@PREFIX CHAR(1),
	    @NUM INT)
RETURNS VARCHAR(5)
AS
BEGIN
    RETURN @PREFIX + RIGHT('0000' +
CAST(@NUM AS VARCHAR(4)), 4)
END;

SELECT DBO.GENERATEID('S', 6);
--EXAMPLE - DBO.GENERATEID('S', 6) = RETURNS 'S0006
