--STORED PROCEDURES FOR SUPPLIERS
CREATE PROCEDURE ADDSUPPLIER
@S_ID VARCHAR(10),
@S_NAME VARCHAR(50), 
@S_ADD VARCHAR(100),
@S_CITY VARCHAR(50),
@S_PHONE VARCHAR(15),
@EMAIL VARCHAR(100)
AS 
BEGIN
     INSERT INTO SUPPLIER
     VALUES (@S_ID, @S_NAME, @S_ADD, @S_CITY, @S_PHONE, @EMAIL);
	 SELECT * FROM SUPPLIER WHERE S_ID = @S_ID;
END;

EXEC ADDSUPPLIER
    @S_ID = 'S0006',
	@S_NAME = 'FRESHELECTRO SUPPLIES',
	@S_ADD = 'NO.56, MARKET YARD',
	@S_CITY = 'HYDERABAD',
	@S_PHONE = '9374835678',
	@EMAIL = 'FRESHELECTRO@SUP.COM';

--STORED PROCEDURES FOR PRODUCTS

CREATE PROCEDURE ADDPRO
@P_ID VARCHAR(10),
@P_DESC VARCHAR(100),
@P_PRICE DECIMAL(10, 2),
@CATEGORY VARCHAR(20),
@S_ID VARCHAR(10)
AS
BEGIN
     INSERT INTO PRODUCT
	 VALUES (@P_ID, @P_DESC, @P_PRICE, @CATEGORY, @S_ID);
	 SELECT * FROM PRODUCT WHERE P_ID = @P_ID;
END;

EXEC ADDPRO
    @P_ID = 'P0016',
    @P_DESC = 'ELECTRIC KETTLE',
    @P_PRICE = 1800.00,
    @CATEGORY = 'HA',
    @S_ID = 'S0002';

--STORED PROCEDURES FOR CUST
CREATE PROCEDURE ADDCUST
@C_ID VARCHAR(10),
@C_NAME VARCHAR(50),
@ADRESS VARCHAR(100),
@CITY VARCHAR(50),
@PHONE VARCHAR(15),
@EMAIL VARCHAR(100),
@DOB DATE
AS
BEGIN
     INSERT INTO CUST
	 VALUES (@C_ID, @C_NAME, @ADRESS, @CITY, @PHONE, @EMAIL, @DOB);
     SELECT * FROM CUST WHERE C_ID = @C_ID;
END;

EXEC ADDCUST
    @C_ID = 'C0006',
	@C_NAME = 'NEHA SINHA',
	@ADRESS = 'G-47 MODEL TOWN',
	@CITY = 'KOLKATA',
	@PHONE = '9825342567',
	@EMAIL = 'NEHA@CUST.COM',
	@DOB = '1991-12-15';

--STORED PROCEDURES FOR ORDERS
CREATE PROCEDURE ADDORDERS
@O_ID VARCHAR(10),
@P_ID VARCHAR(10),
@C_ID VARCHAR(10),
@O_QTY INT 
AS
BEGIN
     INSERT INTO ORDERS (O_ID, O_DATE, P_ID, C_ID, O_QTY)
	 VALUES (@O_ID, GETDATE(), @P_ID, @C_ID, @O_QTY);
	 SELECT * FROM ORDERS WHERE O_ID = @O_ID;
END;

EXEC ADDORDERS
@O_ID = 'O0006',
@P_ID = 'P0004',
@C_ID = 'C0002',
@O_QTY = 3;
