--AUTO-UPDATE STOCK WHEN THE ORDER IS PLACED USING TRIGGER

CREATE TRIGGER TRG_UPDATESTOCKAFTERORDER
ON ORDERS
AFTER INSERT
AS
BEGIN
    UPDATE STOCK
	SET STOCK.SQTY = STOCK.SQTY - INSERTED.O_QTY
	FROM STOCK
	INNER JOIN INSERTED ON STOCK.P_ID = INSERTED.P_ID;
	PRINT 'STOCK QUANTITY UPDATED AFTER PLACING ORDER.'
END;

SELECT * FROM STOCK;
SELECT * FROM ORDERS;

INSERT INTO ORDERS
VALUES ('O0013', GETDATE(), 'P0001', 'C0002', 15);

--CANCEL THE ORDER IF O_QTY IS MORE THAN SQTY FOR THE SAME P_ID USING INSTEAD OF INSERT TRIGGER

CREATE TRIGGER TRG_CHECKSTOCKBEFOREORDER
ON ORDERS
INSTEAD OF INSERT
AS 
BEGIN
    --CHECK IF THE ORDER QUANTITY IS AVAILABLE IN STOCK
	IF EXISTS (SELECT 1 FROM INSERTED I
	           JOIN STOCK S ON I.P_ID = S.P_ID
			   WHERE I.O_QTY > S.SQTY)
	BEGIN
	    --NOT ENOUGH STOCK, CANCEL INSERT AND SHOW MESSAGE
		RAISERROR ('ORDER CANNOT BE PLACED: NOT ENOUGH STOCK AVAILABLE.', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END

	--IF STOCK IS AVAILABLE, INSERT THE ORDER
	INSERT INTO ORDERS (O_ID, O_DATE, P_ID, C_ID, O_QTY)
	SELECT O_ID, O_DATE, P_ID, C_ID, O_QTY
	FROM INSERTED;
END;
